server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, loggers

spring:

  datasource:
    url: jdbc:postgresql://monitor-sensors-postgres:5432/monitor-sensors
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false