---
version: '3.9'

services:

  monitor-sensors:
    container_name: manko-monitor-sensors
    image: manko.project.com/monitor-sensors:latest
    environment:
      spring.profiles.active: docker
    ports:
      - "9093:9093"
    depends_on:
      - monitor-sensors-postgres
    networks:
      - backend_network

  monitor-sensors-postgres:
    container_name: monitor-sensors-postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/monitor-sensors-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network


volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
    name: backend_network
